name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    - name: Restore dependencies
      run: dotnet restore --verbose detailed

    - name: Build solution
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
